services:
  postgres:
    image: 'postgres:13.4'
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - data_postgres:/var/lib/postgresql/data/

  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
    restart: always
    volumes:
      - data_redis:/data

  mariadb:
    image: 'mariadb:10.6'
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

    volumes:
      - data_mariadb:/docker-entrypoint-initdb.d

  minio:
    image: 'quay.io/minio/minio'
    command: server /mnt/data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    restart: always
    environment:
      MINIO_ROOT_USER: $MINIO_KEY
      MINIO_ROOT_PASSWORD: $MINIO_SECRET
    volumes:
      - data_minio:/mnt/data/

  sftp:
    image: 'drakkan/sftpgo:latest'
    ports:
      - 8082:8080
      - 2022:2022
      - 10080:10080
    restart: always
    environment:
      SFTPGO_WEBDAVD__BINDINGS__0__PORT: 10080
    volumes:
      - data_sftp:/mnt/data/
      - data_sftp_home:/var/lib/sftpgo

volumes:
  data_minio:
  data_sftp:
  data_sftp_home:
  data_mariadb:
  data_postgres:
  data_redis:
